Fixed buildsuite on OS X; automatically generate a fully expanded evaluation of the discolors for sourcing.

diff --git a/buildsuite b/buildsuite
--- a/buildsuite
+++ b/buildsuite
@@ -76,8 +76,16 @@ do
 done
 # }}}
 # Dependencies {{{
-if ! type sed &> /dev/null; then echo "ERROR: Missing dependency: sed" 1>&2; exit 1; fi
+SED=$(which gsed||which sed)
+GREP=$(which ggrep||which grep)
+if ! type ${SED} &> /dev/null; then echo "ERROR: Missing dependency: sed" 1>&2; exit 1; fi
 # }}}
+
+# If dircolors is avilable, use it to produce
+# a script ready to be sourced:
+DIRCOLORS=$(which gdircolors||which dircolors)
+if [[ -x ${DIRCOLORS} ]];
+then ${DIRCOLORS} LS_COLORS > LS_COLORS.sh; fi
 
 if [[ ! -d "./test" ]]; then mkdir test || exit 1; fi
 cd test || exit 1
@@ -121,6 +129,6 @@ while read line; do
       touch ./DIRECTORY/"$line"
     fi
   fi
-done < <(sed -r -e '/^[ ]+#/d; /^[^\.\*]/d; /^$/d' ../LS_COLORS | grep -Po '^[\.\*]([A-z0-9]+)' )
+done < <(${SED} -r -e '/^[ ]+#/d; /^[^\.\*]/d; /^$/d' ../LS_COLORS | ${GREP} -Po '^[\.\*]([A-z0-9]+)' )
 
 # vim: ft=sh foldmethod=marker:
